#! /usr/bin/env sh

# This script quickly transpiles any .jsx files in the specified folder
# We need to do this before running tests as Node cannot parse JSX syntax
# It temporarily outputs regular .js files to the _test/ directory
# Tests can import from there instead—this is v hacky

# Usage:
# ./test 2
# Runs test/2.test.js
# or
# ./test 2 solution
# runs test/2.test.js but against solution/ dir

FILE="test/$1.test.js"
DIR="${2:-challenge}"

# Log an error if no argument passed in
[ $# -eq 0 ] && { echo "Please pass a challenge number: e.g. ./tests 1"; exit 1; }

npx esbuild "$DIR"/*.{jsx,js} \
  --jsx=automatic \
  --log-level=error \
  --outdir=_test \
&& \
node --no-warnings "$FILE";
# after tests finish (whether they succeed or fail)
# delete temporary directory
rm -rf _test